# Generated by Django 5.1.3 on 2026-06-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Exercício')),
                ('grupo_muscular', models.CharField(choices=[('PEITO', 'Peitoral'), ('COSTAS', 'Costas'), ('PERNAS', 'Membros Inferiores'), ('BRACOS', 'Braços/Ombros'), ('CORE', 'Abdominais/Core')], max_length=10, verbose_name='Grupo Muscular')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Execução')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('conteudo', models.TextField()),
                ('autor', models.CharField(default='Jhonata', max_length=80)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
    ]
