# Generated by Django 5.1.3 on 2026-07-13 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0002_exercicio_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Ficha')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição/Observações')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Treino',
                'verbose_name_plural': 'Fichas de Treino',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ficha_backup', models.CharField(blank=True, max_length=100, null=True)),
                ('realizado_em', models.DateTimeField(auto_now_add=True)),
                ('duracao_minutos', models.PositiveIntegerField(default=45, verbose_name='Duração (minutos)')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Notas de Execução')),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treinos.fichatreino')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Treino',
                'verbose_name_plural': 'Históricos de Treinos',
                'ordering': ['-realizado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemFichaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(default=3, verbose_name='Séries')),
                ('repeticoes', models.CharField(default='10', max_length=50, verbose_name='Repetições')),
                ('carga', models.PositiveIntegerField(default=0, verbose_name='Carga (kg)')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exercicio')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='treinos.fichatreino')),
            ],
            options={
                'verbose_name': 'Exercício da Ficha',
                'verbose_name_plural': 'Exercícios da Ficha',
            },
        ),
        migrations.CreateModel(
            name='PerfilUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=70.0, verbose_name='Peso (kg)')),
                ('altura', models.FloatField(default=1.7, verbose_name='Altura (m)')),
                ('objetivo', models.CharField(default='Manutenção', max_length=100, verbose_name='Objetivo de Treino')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status de Utilizador',
                'verbose_name_plural': 'Status de Utilizadores',
            },
        ),
    ]
